### ISSUE TITLE
Manage token auth expiration

### ISSUE THREAD

**Issue by gclem** [ovh-ux/ovh-chatbot#7]
Hi,

Is it possible to reply when an auth token is expired please,

Thx

**Comment by bnjjj** [comment]
In fact, when your token is expired chatbot will send you a message to explain that you have to login

**Comment by gclem** [comment]
With a one x token, the bot doesn't answer back that i'm not able to request anymore.

**Comment by bnjjj** [comment]
I don't really understand your issue, maybe a screenshot could be more understandable for all of us :)
